/*
 * MediaImagePanel.java
 *
 * Created on March 29, 2007, 9:21 AM
 */

package de.pd.pjc.gui.media;

import java.awt.Color;
import java.awt.Dimension;

import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;

import de.pd.pjc.Settings;
import de.pd.pjc.bean.FileElement;
import de.pd.pjc.util.IconFactory;

/**
 * 
 * @author petros
 */
public class MediaImagePanel extends javax.swing.JPanel {

	private final static int WIDTH = 500;
	private final static int HEIGHT = 350;

	/** Creates new form MediaImagePanel */
	public MediaImagePanel() {
		initComponents();
		initPanel();
	}

	private void initPanel() {
		setSize(new Dimension(WIDTH, HEIGHT));
		setPreferredSize(new Dimension(WIDTH, HEIGHT));
		setMaximumSize(new Dimension(WIDTH, HEIGHT));
		setBackground(Settings.DEFAULT_BG_COLOR);
		imageButton.setBorder(null);
		imageButton.setFocusCycleRoot(true);
		imageButton.setOpaque(false);
		imageButton.setBackground(Color.black);
		imageButton.setSize(new Dimension(WIDTH, HEIGHT));
		imageButton.setAlignmentX(JButton.CENTER_ALIGNMENT);
		imageButton.setMaximumSize(new Dimension(WIDTH, 270));
	}

	public void showImage(FileElement pFile) {
		Dimension maximumSize = imageButton.getMaximumSize();
		ImageIcon previewImage = IconFactory.getPreviewImage(pFile,
				maximumSize.width, maximumSize.height);
		imageButton.setIcon(previewImage);
		imageButton.setBounds((getWidth() - previewImage.getIconWidth()) / 2, 10,
				previewImage.getIconWidth(), previewImage.getIconHeight());
		imageButton.setBorder(BorderFactory.createLineBorder(Color.white));
		repaint();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        imageButton = new javax.swing.JButton();

        setLayout(null);

        imageButton.setBorderPainted(false);
        imageButton.setContentAreaFilled(false);
        imageButton.setFocusable(false);
        imageButton.setIconTextGap(0);
        imageButton.setRolloverEnabled(false);
        add(imageButton);
        imageButton.setBounds(183, 5, 34, 10);

    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton imageButton;
    // End of variables declaration//GEN-END:variables

}
