/*
 * LightWindow.java
 *
 * Created on October 16, 2007, 7:56 PM
 */

package de.pd.pjc.gui;

import java.awt.HeadlessException;

import de.pd.pjc.Constants;
import de.pd.pjc.FilePatternFilter;
import de.pd.pjc.service.ServiceFactory;

/**
 *
 * @author  petros
 */
public class LightWindow extends javax.swing.JFrame {
   
	private String mPath;
	
    public LightWindow(String pPath) throws HeadlessException {
		super();
		mPath = pPath;
		initComponents();
		init();
	}
    
    private void init() {
   	 FileTablePanel panel = new FileTablePanel(FileTablePanel.SEARCH_FILE_TABLE);
 		ServiceFactory.getMainWindowService().loadFileList(panel.getTable(), Constants.USER_HOME, new FilePatternFilter(), false);
 		ServiceFactory.getMainWindowController().setCurrentTable(panel.getTable());
 		add(panel);
    }

	/** Creates new form LightWindow */
    public LightWindow() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-420)/2, (screenSize.height-465)/2, 420, 465);
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
