/*
 * ManageMimeSettings.java
 *
 * Created on December 30, 2006, 11:54 AM
 */

package de.pd.pjc.gui.dialog;

import java.util.Collection;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import org.springframework.util.StringUtils;

import de.pd.pjc.Settings;
import de.pd.pjc.bean.MimeApplication;
import de.pd.pjc.bean.MimeSettingsBean;
import de.pd.pjc.gui.MainWindowWrapper;
import de.pd.pjc.service.ServiceFactory;
import de.pd.pjc.service.XMLSettingsService;

/**
 *
 * @author  petros
 */
public class ManageMimeSettingsDialog extends javax.swing.JDialog {
    
    private DefaultListModel extListModel = new DefaultListModel();
    private DefaultListModel appListModel = new DefaultListModel();
    
    /** Creates new form ManageMimeSettings */
    public ManageMimeSettingsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBackground(Settings.DEFAULT_BG_COLOR);
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        int width = getWidth();
        int height = getHeight();
        setBounds((screenSize.width-width)/2, (screenSize.height-height)/2, width, height);
        
        loadMimes();
        
    }
    
    private void loadMimes() {
   	 XMLSettingsService settingsService = ServiceFactory.getXMLSettingsService();
   	 
   	 Collection<MimeSettingsBean> mimeSettings = settingsService.getAllMimeSettings();
   	 extListModel.clear();
   	 for (MimeSettingsBean mimeSettingsBean : mimeSettings) {
			extListModel.addElement(mimeSettingsBean);
		}
   	 
   	 if(extListModel.getSize() > 0) {
     	  extList.setSelectedIndex(0);
       }
       extList.requestFocusInWindow();
       appSettingPanel.setVisible(false);
       showExtInfo();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        extList = new javax.swing.JList();
        addExtButton = new javax.swing.JButton();
        removeExtButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        removeAppButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        appList = new javax.swing.JList();
        addAppButton = new javax.swing.JButton();
        appSettingPanel = new javax.swing.JPanel();
        appNameLabel = new javax.swing.JLabel();
        tfAppName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfCommand = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfIcon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfArgs = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbDefault = new javax.swing.JCheckBox();
        saveAppSettingsButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Mime Settings");
        setBackground(new java.awt.Color(153, 255, 102));
        extList.setModel(extListModel);
        extList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        extList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                extListKeyReleased(evt);
            }
        });
        extList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                extListMouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(extList);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 31, 130, 300);

        addExtButton.setMnemonic('d');
        addExtButton.setText("Add");
        addExtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExtButtonActionPerformed(evt);
            }
        });

        getContentPane().add(addExtButton);
        addExtButton.setBounds(10, 330, 59, 25);

        removeExtButton.setMnemonic('e');
        removeExtButton.setText("Remove");
        getContentPane().add(removeExtButton);
        removeExtButton.setBounds(70, 330, 70, 25);

        jLabel1.setBackground(new java.awt.Color(231, 231, 189));
        jLabel1.setText("Extensions");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 68, 15);

        jPanel1.setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Applications"));
        removeAppButton.setMnemonic('R');
        removeAppButton.setText("Remove");
        removeAppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAppButtonActionPerformed(evt);
            }
        });

        jPanel1.add(removeAppButton);
        removeAppButton.setBounds(190, 50, 70, 25);

        appList.setModel(appListModel);
        appList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        appList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                appListKeyReleased(evt);
            }
        });
        appList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appListMouseClicked(evt);
            }
        });

        jScrollPane2.setViewportView(appList);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(10, 20, 170, 110);

        addAppButton.setMnemonic('A');
        addAppButton.setText("Add");
        addAppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAppButtonActionPerformed(evt);
            }
        });

        jPanel1.add(addAppButton);
        addAppButton.setBounds(189, 20, 70, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(150, 180, 270, 140);

        appSettingPanel.setLayout(null);

        appSettingPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Application Settings"));
        appNameLabel.setLabelFor(tfAppName);
        appNameLabel.setText("Name");
        appSettingPanel.add(appNameLabel);
        appNameLabel.setBounds(10, 20, 80, 20);

        appSettingPanel.add(tfAppName);
        tfAppName.setBounds(80, 20, 190, 20);

        jLabel2.setLabelFor(tfCommand);
        jLabel2.setText("Command");
        appSettingPanel.add(jLabel2);
        jLabel2.setBounds(10, 40, 64, 15);

        appSettingPanel.add(tfCommand);
        tfCommand.setBounds(80, 40, 190, 20);

        jLabel3.setText("Icon");
        appSettingPanel.add(jLabel3);
        jLabel3.setBounds(10, 80, 26, 15);

        appSettingPanel.add(tfIcon);
        tfIcon.setBounds(80, 80, 190, 20);

        jLabel4.setText("Args");
        appSettingPanel.add(jLabel4);
        jLabel4.setBounds(10, 60, 29, 15);

        appSettingPanel.add(tfArgs);
        tfArgs.setBounds(80, 60, 190, 20);

        jLabel5.setText("Default");
        appSettingPanel.add(jLabel5);
        jLabel5.setBounds(10, 100, 60, 15);

        cbDefault.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        cbDefault.setMargin(new java.awt.Insets(0, 0, 0, 0));
        appSettingPanel.add(cbDefault);
        cbDefault.setBounds(80, 100, 20, 13);

        saveAppSettingsButton.setMnemonic('S');
        saveAppSettingsButton.setText("Save");
        saveAppSettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAppSettingsButtonActionPerformed(evt);
            }
        });

        appSettingPanel.add(saveAppSettingsButton);
        saveAppSettingsButton.setBounds(10, 120, 70, 20);

        getContentPane().add(appSettingPanel);
        appSettingPanel.setBounds(150, 20, 280, 150);

        closeButton.setMnemonic('C');
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        getContentPane().add(closeButton);
        closeButton.setBounds(330, 330, 69, 25);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-440)/2, (screenSize.height-402)/2, 440, 402);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void removeAppButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAppButtonActionPerformed
   	 XMLSettingsService settingsService = ServiceFactory.getXMLSettingsService();
   	 
   	 MimeApplication app = (MimeApplication) appList.getSelectedValue();
   	 MimeSettingsBean ext = (MimeSettingsBean) extList.getSelectedValue();
   	 
   	 settingsService.deleteMimeSettings(ext.getExtension(), app.getName());
   	 loadMimes();
   	 
    }//GEN-LAST:event_removeAppButtonActionPerformed

    private void addAppButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAppButtonActionPerformed
   	 tfAppName.setText("");
   	 tfCommand.setText("");
   	 tfArgs.setText("");
   	 tfIcon.setText("");
   	 cbDefault.setSelected(false);
   	 appSettingPanel.setVisible(true);
    }//GEN-LAST:event_addAppButtonActionPerformed

    private void saveAppSettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAppSettingsButtonActionPerformed
       
   	 if(!StringUtils.hasLength(tfAppName.getText())) {
   		 JOptionPane.showMessageDialog(this, "Name must not be null", "Error", JOptionPane.ERROR_MESSAGE);
   		 return;
   	 }
   	 
   	 if(!StringUtils.hasLength(tfCommand.getText())) {
   		 JOptionPane.showMessageDialog(this, "Command must not be null", "Error", JOptionPane.ERROR_MESSAGE);
   		 return;
   	 }
   	 
   	 XMLSettingsService settingsService = ServiceFactory.getXMLSettingsService();
   	 
   	 MimeApplication app = new MimeApplication();
       app.setName(tfAppName.getText());
       app.setCommand(tfCommand.getText());
       app.setArgs(tfArgs.getText());
       app.setIcon(tfIcon.getText());
       app.setDefault(cbDefault.isSelected());
       
       MimeSettingsBean mimeSettings = (MimeSettingsBean) extList.getSelectedValue();
       
       settingsService.storeMimeSettings(mimeSettings.getExtension(), app);
       
       loadMimes();
        
    }//GEN-LAST:event_saveAppSettingsButtonActionPerformed

    private void addExtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExtButtonActionPerformed
   	 String ext = JOptionPane.showInputDialog(this, "Please enter the extension", "Add new extension", JOptionPane.PLAIN_MESSAGE);
   	 if(ext == null) {
   		 return;
   	 }
   	 XMLSettingsService settingsService = ServiceFactory.getXMLSettingsService();
   	 settingsService.storeMimeSettings(ext, null);
   	 loadMimes();
   	 
    }//GEN-LAST:event_addExtButtonActionPerformed

    private void extListKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_extListKeyReleased
       showExtInfo();
    }//GEN-LAST:event_extListKeyReleased

    private void appListKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_appListKeyReleased
   	 if(MainWindowWrapper.isNavKeyPressed(evt)) {
   		 showAppInfo();
   	 }
    }//GEN-LAST:event_appListKeyReleased

    private void appListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appListMouseClicked
   	 showAppInfo();
    }//GEN-LAST:event_appListMouseClicked

    private void showAppInfo() {
   	 MimeApplication app = (MimeApplication) appList.getSelectedValue();
   	 tfAppName.setText(app.getName());
   	 tfCommand.setText(app.getCommand());
   	 tfArgs.setText(app.getArgs());
   	 tfIcon.setText(app.getIcon());
   	 cbDefault.setSelected(app.isDefault());
   	 appSettingPanel.setVisible(true);
    }
    
    private void extListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_extListMouseClicked
        showExtInfo();
    }//GEN-LAST:event_extListMouseClicked

	private void showExtInfo() {
		MimeSettingsBean mimeSettings = (MimeSettingsBean) extList.getSelectedValue();
        Collection<MimeApplication> apps = mimeSettings.getApps();
        appListModel.clear();
        for (MimeApplication app : apps) {
			appListModel.addElement(app);
        }
        if(appListModel.getSize() > 0) {
      	  appList.setSelectedIndex(0);
      	  showAppInfo();
        } else {
      	  appSettingPanel.setVisible(false);
        }
	}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAppButton;
    private javax.swing.JButton addExtButton;
    private javax.swing.JList appList;
    private javax.swing.JLabel appNameLabel;
    private javax.swing.JPanel appSettingPanel;
    private javax.swing.JCheckBox cbDefault;
    private javax.swing.JButton closeButton;
    private javax.swing.JList extList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton removeAppButton;
    private javax.swing.JButton removeExtButton;
    private javax.swing.JButton saveAppSettingsButton;
    private javax.swing.JTextField tfAppName;
    private javax.swing.JTextField tfArgs;
    private javax.swing.JTextField tfCommand;
    private javax.swing.JTextField tfIcon;
    // End of variables declaration//GEN-END:variables
    
}
